<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>CourseDeveloper.Worker</RootNamespace>
    <UserSecretsId>dotnet-CourseDeveloper.Worker</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CourseDeveloper.Core\CourseDeveloper.Core.csproj" />
    <ProjectReference Include="..\CourseDeveloper.Infrastructure\CourseDeveloper.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.0" />
    <PackageReference Include="Npgsql" Version="9.0.3" />
  </ItemGroup>
</Project>
